### ISSUE TITLE
consideration of formatting?

### ISSUE THREAD

**Issue by SinaB0ck** [cs6-uniwue/Variance-Viewer#4]
The following two versions:

1.)
```<hi rend="antiqua">Ave Maria’s</hi>```

2.)

```<hi rend="Arial">Ave Maria's</hi>```

currently result in:

```
<hi rend="antiqua">Ave <app>
<lem>Maria’s</lem>
<rdg>Maria's</rdg>
</app></hi>
```

Which means that the formatting by which the variance differ by will be lost. In the event of consideration of formatting is a requirement this tool should be able to deal with the output should look like this:

```<app>
<lem><hi rend="antiqua">Ave Maria’s</hi></lem>
<rdg><hi rend="Arial">Ave Maria's</hi></rdg>
</app>```

**Comment by NesbiDevelopment** [comment]
Thank you for bringing this to my attention.
The differences between those two are seen as word changes and I can see why the second rend could get lost.
I'll look into it.
